<a href="https://colab.research.google.com/github/Adwaithgs45/DataDcience-assignment/blob/main/14_08_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Daily Task day 14***

1.**Write a function to find the maximum of three numbers and return the result**

In [ ]:
def maximum(a,b,c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return

a = int(input("Enter the 1st value:"))
b = int(input("Enter the 2nd value:"))
c = int(input("Enter the 3rd value:"))
Maximum_Value = maximum(a,b,c)
print("Maximum Value is : ",Maximum_Value)

Enter the 1st value:88
Enter the 2nd value:89
Enter the 3rd value:87
Maximum Value is :  89


2.Implement a function to calculate the area of a circle given the radius.

In [ ]:
def radius(a):
  area = 3.14*a**2
  return area

radius(2)

12.56

3.Create a function to check if a given number is prime or not, and return a boolean result.

In [ ]:
def prime_number(a):
  if a<=1:
    return False
  if a==2:
    return True
  if a %2 == 0:
    return False
  i=3
  while i*i<=a:
    if a %i==0:
      return False
    i+=2
  return True

a=int(input("Enter the number:"))
result = prime_number(a)
print(result)

Enter the number:7
True


4.Create a function to check if a given string is a palindrome and return a boolean result

In [ ]:
def palindrome(s):
    s = s.lower()
    return s == s[::-1]

print(palindrome("Malayalam"))
print(palindrome("Hindi"))


True
False


 5.Implement a function to calculate the sum of all numbers in a list and
return the sum.

In [ ]:
def sum_of_list(numbers):

    total = sum(numbers)
    return total
numbers = [77,88,99,55,44]
result = sum_of_list(numbers)
print(result)

363


 6.Create a function to find the average of a list of numbers and return the
average value.

In [ ]:
def average(numbers):
  total=sum(numbers)
  number_of_values=len(numbers)
  average=total/number_of_values
  return average

numbers =[28,26,45,55,77]
result=average(numbers)
print(result)

46.2


7.Write a function to find the kth largest element in an unsorted list

In [ ]:
def kth_largest(nums, a):
    nums.sort(reverse=True)
    return nums[a - 1]





In [ ]:
nums = [45,56,85,99,41,52,77]
a = 1
print(kth_largest(nums, a))

99


8.Write a recursive function to find the sum of digits of a positive integer.

In [ ]:
def sum(n):
    if n < 10:
        return n
    else:
        return n % 10 + sum(n // 10)


sum(12676)



22

9.Write a recursive function to calculate the power of a number.

In [ ]:
def power(base, exponent):
    if exponent == 0:
        return 1
    else:
        return base * power(base, exponent - 1)

power(5,3)

125

10.Create a function to find the greatest common divisor (GCD) of two
numbers using Euclidean algorithm.

In [ ]:
def greatest_common_divisor(a, b):
    while b != 0:
        a, b = b, a % b
    return a


In [ ]:
greatest_common_divisor(100,4)

4

11.Create a 1D array of numbers from 0 to 9.

In [ ]:
import numpy as np

In [ ]:
randum_array=np.arange(0,10)
randum_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

12. Create a 2D array of shape (3, 3) with values ranging from 1 to 9.

In [ ]:
array_1d=np.arange(1,10)
array_2d=array_1d.reshape(3,3)
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

13.Create a 3x3 identity matrix.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. Create an array of 10 random numbers and find the mean and standard
deviation.

In [ ]:
randum_numbers = np.random.rand(10)
mean=np.mean(randum_numbers)
standard_deviation=np.std(randum_numbers)


In [ ]:
randum_numbers

array([0.19378239, 0.66568367, 0.96851988, 0.60256517, 0.95651444,
       0.82135311, 0.60224323, 0.12071234, 0.64370644, 0.90590312])

In [ ]:
mean

0.6480983788743698

In [ ]:
standard_deviation

0.2798775531777221

15.Create a 1D array of numbers from 10 to 20 and extract the first 5 elements.

In [ ]:
array=np.arange(10,21)
first_5_elements=array[:5]
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
first_5_elements

array([10, 11, 12, 13, 14])

16. Create a 2D array of shape (4, 4) and extract the second row.

In [ ]:
array=np.arange(1,17).reshape((4,4))
second_row=array[1]
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
second_row

array([5, 6, 7, 8])

17. Create two 1D arrays of length 5 with values ranging from 1 to 5 and 6 to 10, Perform element-wise addition.

In [ ]:
array_1=np.arange(1,6)
array_2=np.arange(6,11)
result=array_1+array_2

In [ ]:
array_1

array([1, 2, 3, 4, 5])

In [ ]:
array_2

array([ 6,  7,  8,  9, 10])

In [ ]:
result

array([ 7,  9, 11, 13, 15])

18.. Create a 1D array of 10 random numbers and replace all elements less than
0.5 with 0

In [ ]:
randum_numbers=np.random.rand(10)

randum_numbers

array([0.30212845, 0.16697729, 0.89189568, 0.04981397, 0.71789964,
       0.19283291, 0.67797368, 0.73426908, 0.18421997, 0.46913422])

In [ ]:
randum_numbers[randum_numbers<0.5]=0
randum_numbers

array([0.        , 0.        , 0.89189568, 0.        , 0.71789964,
       0.        , 0.67797368, 0.73426908, 0.        , 0.        ])